// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlp8KOohMfpbkWPm248_9qqMAAtuip-4',
    appId: '1:132095857967:web:ddb3288e6c73246d517dda',
    messagingSenderId: '132095857967',
    projectId: 'socialmedia-a98e0',
    authDomain: 'socialmedia-a98e0.firebaseapp.com',
    storageBucket: 'socialmedia-a98e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_cvSfkePWuRwqPFtTQO7SVYyfUx-k4Fs',
    appId: '1:132095857967:android:119b2513697ba5b8517dda',
    messagingSenderId: '132095857967',
    projectId: 'socialmedia-a98e0',
    storageBucket: 'socialmedia-a98e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDf7aDpiNeEiuKN28f2TCWMS4OzfkkEM',
    appId: '1:132095857967:ios:d7dc2fd41ed478c1517dda',
    messagingSenderId: '132095857967',
    projectId: 'socialmedia-a98e0',
    storageBucket: 'socialmedia-a98e0.firebasestorage.app',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWDf7aDpiNeEiuKN28f2TCWMS4OzfkkEM',
    appId: '1:132095857967:ios:d7dc2fd41ed478c1517dda',
    messagingSenderId: '132095857967',
    projectId: 'socialmedia-a98e0',
    storageBucket: 'socialmedia-a98e0.firebasestorage.app',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLlp8KOohMfpbkWPm248_9qqMAAtuip-4',
    appId: '1:132095857967:web:8e37abbdc0740346517dda',
    messagingSenderId: '132095857967',
    projectId: 'socialmedia-a98e0',
    authDomain: 'socialmedia-a98e0.firebaseapp.com',
    storageBucket: 'socialmedia-a98e0.firebasestorage.app',
  );
}
